### ISSUE TITLE
Properly size profile images

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/contributions-web#30]
**Describe the bug**
The profile pictures of users as served by Github are bigger than what they appear i.e. 460x460

**To Reproduce**
1. Go to the list of users
2. Notice the size i.e. height and width of the profile pic.
3. Compare the size of the pic with the original one as served.

**Expected behavior**
The profile pictures height and width should be as rendered on the page (i.e. 80x80)

**Screenshots**
![image](https://user-images.githubusercontent.com/7326249/144220499-533b757b-22ff-4923-8196-6236b64e393f.png)

**Comment by thread-koder** [comment]
This issue can not be fixed as the GitHub API does not support image transformations
