### ISSUE TITLE
Website doesn't have an icon

### ISSUE THREAD

**Issue by thread-koder** [jordanopensource/contributions-web#60]
**Describe the bug**
The website doesn't have an icon

**To Reproduce**
1. Go to '[contributions](https://contributions.josa.ngo/)'
2. Look at the tab icon you will see there is no icon

**Expected behavior**
The website should have an icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/48834143/160645635-4aec2568-372b-4b2a-a000-78b299d1c997.png)

**Comment by mahasneh** [comment]
Here is a list of favicons to be used:

- 32x32:
![favicon-32](https://user-images.githubusercontent.com/7326249/161944379-ceb0c3d4-60ed-426f-9b74-632147be5e8e.png)

- 64x64:
![favicon-64](https://user-images.githubusercontent.com/7326249/161944030-1702a391-b86b-454a-bedc-52d06bbf14f7.png)

- 128x128:
![favicon-128](https://user-images.githubusercontent.com/7326249/161944414-86008a05-ae42-499c-a43b-6e4a70e7c0ec.png)

- 256x256:
![favicon-256](https://user-images.githubusercontent.com/7326249/161944428-6f0d9972-1722-471a-ab6a-52a4eaf71a5c.png)
