### ISSUE TITLE
A bug in the contributors list counter

### ISSUE THREAD

**Issue by itsmohmans** [jordanopensource/contributions-web#79]
**Describe the bug**
When I go to the last page (page number 369) in the contributors list, the number besides the user that indicates his order in the list is wrong, all the users in that page have the same wrong number. Even when I change the page, the same number sticks. The wrong number being shown is 15 when the filtered period is last 30 days, and 67 when the period is this year.

![image](https://user-images.githubusercontent.com/55551984/209870917-92b6bbcc-7a6b-4d64-955b-3cde32a98ea5.png)
![image](https://user-images.githubusercontent.com/55551984/209870941-24302986-8938-41fe-9e87-77e5b6d890a5.png)

and of course the correct number of users should be 1979 according to the API call (or even by calculating 396*5). But the problem here isn't just counting, because at some point it sticks to the number and keep it the same for all users.

When I tried using `Next` button in the pagination (or just navigating using numbers, one by one) to navigate through pages, I got a different (even more strange) behavior, in the second page I've got 2 users with the same number 6.

![image](https://user-images.githubusercontent.com/55551984/209871456-b3bec1ab-2e35-41ae-98c6-14e526256c3c.png)

Then on the third page I got 3 users with number 9

![image](https://user-images.githubusercontent.com/55551984/209871539-be1ff000-b04f-408a-81a3-e065582e444e.png)

Then it kept counting wrong as the screenshots below show

![image](https://user-images.githubusercontent.com/55551984/209871703-823d98e8-865e-445a-8328-fa21e715bc38.png)
![image](https://user-images.githubusercontent.com/55551984/209871672-8cc18627-732a-4886-890e-75eb0f8d19d2.png)

Everything worked again as expected when I changed the filtered period.

**To Reproduce**
1. Go to https://contributions.josa.ngo/contributors
2. Scroll down to 'Top Developers in Jordan' list section
3. Navigate through pages as described above

**Expected behavior**
The list should show the correct number of the user in any page.

**Screenshots**
_In the bug description._

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox 108.0.1

**Smartphone (please complete the following information):**
 - Device Xiaomi Redmi Note 8
 - OS: Android 11 - Lineage OS 18.1
 - Browser Firefox
 - Version 108.1.1

_Note_: Same problem on mobile in landscape mode since the number isn't even shown in portrait mode.

**Additional context**
None.

**EDIT:  I just realized that this is supposed to be a rank, not a counter. And duplicate ranks mean the same score. So this is _not_ an issue.**

**Comment by mahasneh** [comment]
This is by design. Users with same score should be ranked the same. So, you have multiple users ranked 15 if they all have the same score.
See: Dense Ranking ([Wikipedia](https://en.wikipedia.org/wiki/Ranking#Dense_ranking_(%221223%22_ranking))):

> In dense ranking, items that compare equally receive the same ranking number, and the next items receive the immediately following ranking number.
