### ISSUE TITLE
Organization's Github Username should be Clickable

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/contributions-web#85]
**Is your feature request related to a problem? Please describe.**
The username of the organization should be clickable in the 'Organizations' page.

**Describe the solution you'd like**
Once you click the organization's github username you are redirected to their github profile.

**Comment by thamudi** [comment]
Fixed in PR #86, awaiting approval.

___

How it will look after this branch will be merged.

![image](https://github.com/jordanopensource/contributions-web/assets/18720062/46c71088-6b76-43d3-bdbe-25625df7ded4)

**Comment by thread-koder** [comment]
I will be closing this issue as it has been fixed.
