### ISSUE TITLE
Feature Request: Make User Avatars Clickable to Redirect to Github Profiles

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/contributions-web#91]
**Is your feature request related to a problem? Please describe.**
Currently, on contributions.josa.ngo, user profiles and organization user listings display user avatars alongside usernames. However, these avatars are not clickable, and users can only navigate to a user's Github profile by clicking on their username link. This can be somewhat inconvenient for users who might expect to click on the user avatar to access the Github profile.

**Describe the solution you'd like**
I would like to request a feature enhancement that makes user avatars clickable in both the list of user contributors and organization users. When a user clicks on a user's avatar, it should redirect them to the respective user's Github profile.

**Describe alternatives you've considered**
One alternative could be to click the link next to the user avatar. Making the user avatar clickable simplifies the user experience and aligns with common expectations.

**Additional context**
Adding this feature would improve the user experience on our platform by providing an intuitive way to access a user's Github profile directly from their avatar. This change would make the platform more user-friendly and enhance user engagement with user profiles and organization user listings.

**Comment by bhishekprajapati** [comment]
Implemented! Please review my PR
