### ISSUE TITLE
Bug: Margins for .header-title Elements Causing Text Overflow

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/contributions-web#92]
**Describe the bug**
The `.header-title` elements on the website are not provided with a `margin-right` style attribute. As a result, the text of these titles extends beyond their containers, causing a display issue, as shown in the provided screenshot.

**To Reproduce**
1. Go to any page on the website.
2. Locate a `.header-title` element, typically found in the header or other sections.
3. Observe that the text of the title extends beyond its container, as shown in the screenshot.

**Expected behavior**
The `.header-title` elements should be given a `margin` style attribute for both right and left (horizontal) to ensure that it will maintain a visually pleasing and balanced layout.

**Screenshots**
![image](https://github.com/jordanopensource/contributions-web/assets/7326249/64b1a19d-ee97-43d5-86a4-6ab529902cb2)

**Additional context**
This issue affects the overall appearance and readability of the website. Adding the `margin-right` style attribute to `.header-title` elements will help ensure that titles are properly contained within their designated areas, providing a more polished and user-friendly presentation.

**Comment by bhishekprajapati** [comment]
Hey @mahasneh, I'd like to contribute to fix this bug. Can you assign me?

**Comment by bhishekprajapati** [comment]
Fixed it. Review my PR!
