### ISSUE TITLE
Bug: Incorrect Styling of 'Last Updated' Element Causing Text Overflow

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/contributions-web#93]
**Describe the bug**
The "Last Updated" text/element on the website is styled with an arbitrary `margin-right` value of `6rem` (`.mr-6`). This styling causes the element to overflow from the page container, which is inconsistent with the styling of other sections on the website.

**To Reproduce**
1. Go to any page on the website.
2. Locate the "Last Updated" text/element, typically found in the footer or other sections.
3. Observe that the element is given a `margin-right` value of `6rem`, causing it to overflow from the page container.

**Expected behavior**
The "Last Updated" text/element should be styled consistently with other sections on the website, ensuring that it does not overflow from the page container. This will provide a more visually pleasing and organized layout.

**Screenshots**
Current behavior:
![image](https://github.com/jordanopensource/contributions-web/assets/7326249/20d8e1e9-d7c6-439f-9a31-4df35275f3a4)

Expected behavior:
![image](https://github.com/jordanopensource/contributions-web/assets/7326249/3764ad48-b3e4-480d-932e-f88439414a8c)

On `.lg` screens:
Current behavior:
![image](https://github.com/jordanopensource/contributions-web/assets/7326249/b9cb5dac-1a80-4ac1-a277-20a421a76781)

Expected behavior:
![image](https://github.com/jordanopensource/contributions-web/assets/7326249/80e0139f-c1e1-44cf-8bd9-fe508c561937)

**Additional context**
This issue affects the overall appearance and layout of the website, leading to an inconsistent and less polished user experience. Correcting the styling of the "Last Updated" element will ensure that it aligns with the design and layout standards of the rest of the website, providing a more cohesive and visually appealing presentation.

**Comment by bayan-alkhatib** [comment]
@thread-koder  can you please assign this issue to me, I'd like to work on it.

**Comment by thread-koder** [comment]
@bayan-alkhatib absolutely.
